### ISSUE TITLE
Fetch elevation data from ScienceBase instead of EPQS

### ISSUE THREAD

**Issue by AndyMcAliley** [USGS-R/lake-temperature-lstm-static#23]
Obtaining elevations using the USGS Elevation Point Query Service is slow. A faster way would be to download the metadata from [Jared's data release](https://www.sciencebase.gov/catalog/item/60341c3ed34eb12031172aa6), and join with our metadata on `site_id`.

_Suggested by @jread-usgs in https://github.com/USGS-R/lake-temperature-lstm-static/issues/9#issuecomment-1040767786_

**Comment by jread-usgs** [comment]
FYI that elevation is now formally in the pipeline via this https://github.com/USGS-R/lake-temperature-model-prep/issues/285
