### ISSUE TITLE
URGENT - associated paper?

### ISSUE THREAD

**Issue by jpadilla-usgs** [USGS-R/lake-temperature-lstm-static#58]
Hi all,

I just got off a call with Joe. Is this work going to be written up in a published paper? If so, we may need to change tack on how we are packaging up the associated [data release](https://github.com/USGS-R/lake-temp-lstm-static-data-release) and this repo.

Option 1 - move this repo to gitlab and complete official software release so that this work is citable
Option 2 - roll this repo and the existing data release together into a model release (similar to a recent approach taken in the DRB).

I know that we have collaborators who are depending on the data release, so Joe is following up with our BAO to see if there is something we can do to stop the data release from stalling out.

I have tagged folks who are either involved in this repo or have had similar experiences (I left Andy off until he returns from family leave).

**Comment by lindsayplatt** [comment]
No, this was not going into a published paper as it is using a previously published model with one code change (edited to be able to predict at more than one depth). Our `process-description` in the metadata states:

> Lake temperature estimates were generated using an Entity-Aware Long Short-Term Memory network (EA-LSTM), as described by Kratzert et al., 2019

Andy would be able to provide more information, but as far as I know, he used the exact model code published by Kratzert in that paper (see https://hess.copernicus.org/articles/23/5089/2019/#section5) with [this one change](https://github.com/USGS-R/lake-temperature-lstm-static/commit/1e4e663a3ca4e9ce8929524368d2355851eb179f).

**Comment by lindsayplatt** [comment]
We viewed it similar to GLM - we are using a published model with minor changes to produce our output but are not re-publishing GLM.

**Comment by jzwart** [comment]
And the data release is not, at least at the moment, going to be used in a manuscript led by USGS authors?

**Comment by lindsayplatt** [comment]
No, I am not aware of any manuscripts using the data published here from us. Collaborators may use the data in other publications with us as co-authors, though.

**Comment by padilla410** [comment]
Awesome, thank you for the response, @lindsayplatt. I’ll keep moving this thing along while you’re on vacation. 

@jzwart ill follow up with you for questions as needed

**Comment by jpadilla-usgs** [comment]
I am resolving this issue. Lindsay and I had a quick chat about the fact that the model was published so we were able to move the DR to dissemination
