### ISSUE TITLE
Include elevations in lake metadata

### ISSUE THREAD

**Issue by AndyMcAliley** [USGS-R/lake-temperature-lstm-static#9]
We want to use elevation as a lake attribute. It's not included in lake_metadata.csv, so we'll need to add it somehow.

**Comment by jread-usgs** [comment]
We have an open issue for the prep pipeline for this [here](https://github.com/USGS-R/lake-temperature-model-prep/issues/285). 

Another option is to do a join on the `site_id` between the data release you are using and Jared's data release metadata table, which has the elevation data.

**Comment by AndyMcAliley** [comment]
Thanks! I wrote a function to pull elevations from the USGS Elevation Point Query Service using lake centroids. It is slow, though, and it would be good to use an existing data release.
